#!/bin/bash

# qanalyze_bqs.sh - queue a GLAST analysis run on the Lyon cluster
#                 - BQS version
#                 - OBSOLETE, will not be updated after Nov 2011
# Stephen Fegan - sfegan@llr.in2p3.fr - 2008-10-21
# $Id: qanalyze_bqs.sh 3389 2011-11-22 15:03:45Z sfegan $

PWD=`/bin/pwd`
CP='cp -pv'

CMD_RA="$1"
CMD_DEC="$2"
CMD_NAME=`sanitize_name.sh "$3"`
CMD_DIR="$4"

if test "$CMD_RA" == "" -o "$CMD_DEC" == "" -o "$CMD_NAME" == "" -o "$CMD_DIR" == ""
then
  echo "usage: $0 ra dec source_name output_directory [settings]"
  exit
fi

ALLARGS="$@"

shift
shift
shift
shift

ARGS="$@"

if test -f $HOME/.qanalyzerc
then
  . $HOME/.qanalyzerc
fi

while test $# -ne 0
do
  var=`echo "$1" | cut -d= -f1`
  if test "$var" == "RESTART" -o "$var" == "TIMELIMIT" \
       -o "$var" == "MEMLIMIT" -o "$var" == "SCRLIMIT" \
       -o "$var" == "JOBPREFIX" -o "$var" == "CPUPLATFORM" \
       -o "$var" == "QSUB" -o "$var" == "Q"
  then
    export "$1"
  fi
  shift
done

if test "$RESTART" \!= ""
then
  RESTART=`echo $RESTART | tr '[:lower:]' '[:upper:]'`
fi

if test \! -d "$CMD_DIR"
then
  echo Directory does not exists: "$CMD_DIR"
  exit
fi

if test "$Q" \!= ""
then
  if test "$TIMELIMIT"   == ""; then TIMELIMIT=${Q}MAX; fi
  if test "$MEMLIMIT"    == ""; then MEMLIMIT=${Q}MAX; fi
  if test "$SCRLIMIT"    == ""; then SCRLIMIT=${Q}MAX; fi
fi

if test "$TIMELIMIT"   == ""; then TIMELIMIT=TMAX; fi
if test "$TIMELIMIT"   == "MAX"; then TIMELIMIT="TMAX"; fi
if test "$MEMLIMIT"    == ""; then MEMLIMIT=TMAX; fi
if test "$SCRLIMIT"    == ""; then SCRLIMIT=TMAX; fi
if test "$CPUPLATFORM" == ""; then CPUPLATFORM="LINUX"; fi
if test "$JOBPREFIX"   == ""; then JOBPREFIX=GLAST; fi
if test "$QSUB"        == ""; then QSUB=qsub; fi

# Ref: http://cctools.in2p3.fr/mrtguser/info_bqs_class_config.php

if test "$TIMELIMIT"   == "GMAX"; then TIMELIMIT=680000; fi
if test "$MEMLIMIT"    == "GMAX"; then MEMLIMIT=3072; fi
if test "$SCRLIMIT"    == "GMAX"; then SCRLIMIT=30720; fi

if test "$TIMELIMIT"   == "TMAX"; then TIMELIMIT=4286000; fi
if test "$MEMLIMIT"    == "TMAX"; then MEMLIMIT=4096; fi
if test "$SCRLIMIT"    == "TMAX"; then SCRLIMIT=30720; fi

OUTDIR=`cd "$CMD_DIR"; /bin/pwd`
SCRIPTDIR=`dirname $0`

RAND=`mktemp -u XXXXXXXXXX`
JOBNAME="${JOBPREFIX}_${CMD_NAME}_${RAND}"

LIMITOPT="-l t=${TIMELIMIT},M=${MEMLIMIT}MB,scr=${SCRLIMIT}MB"
if test "$Q" \!= ""
then
  LIMITOPT="${LIMITOPT} -q $Q"
fi

# *****************************************************************************
# *****************************************************************************
#
# SCRIPT STARTS HERE
#
# *****************************************************************************
# *****************************************************************************

#cat <<EOF
${QSUB} <<EOF
#!/bin/bash
#PBS $LIMITOPT
#PBS -l platform=${CPUPLATFORM},u_sps_glast
#PBS -eo 
#PBS -V 
#PBS -N $JOBNAME

###############################################################################
# Script automatically generated by $0 on behalf of $USER
###############################################################################

echo '$0 $ALLARGS'
echo 'Running on:' "`hostname`"
echo 'Uptime:    ' "`uptime`"

if test "$GLAST_SCI" \!= ""
then
  export GLAST_SCI="$GLAST_SCI"
fi
if test "$GLAST_BIN" \!= ""
then
  export GLAST_BIN="$GLAST_BIN"
fi
if test "$GLAST_REL" \!= ""
then
  export GLAST_REL="$GLAST_REL"
fi
if test "$GLAST_EXT" \!= ""
then
  export GLAST_EXT="$GLAST_EXT"
fi
if test "$ROOTSYS" \!= ""
then
  export ROOTSYS="$ROOTSYS"
fi
if test "$HEADAS" \!= ""
then
  export HEADAS="$HEADAS"
  . \$HEADAS/headas-init.sh
fi
if test "$PATH" \!= ""
then
  export PATH="$PATH"
fi
if test "$LD_LIBRARY_PATH" \!= ""
then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
fi

#if test "\$HEADAS" == ""
#then
#  export GLAST_SCI="$GLAST_SCI"
#  export GLAST_REL="$GLAST_REL"
#  export GLAST_EXT="$GLAST_EXT"
#  export HEADAS="$HEADAS"
#  . \$HEADAS/headas-init.sh
#  export PATH=\$HOME/bin:\$HOME/scripts:\$GLAST_SCI/bin:\$GLAST_REL/bin:\$PATH
#fi

PFILES=.:\$PFILES
cd \$TMPBATCH

if test "$RESTART" \!= "" -a "$RESTART" \!= "NOCOPY"
then
  CMD="$CP $OUTDIR/${CMD_NAME}* $OUTDIR/model.xml ."
  echo \$CMD
  \$CMD
elif test "$RESTART" \!= "NOCOPY"
then
  CMD="$CP $OUTDIR/${CMD_NAME}_model.xml $OUTDIR/model.xml ."
  echo \$CMD
  \$CMD
  CMD="$CP $OUTDIR/${CMD_NAME}_analysis*.log ."
  echo \$CMD
  \$CMD
fi

logi=0
while test -f ${CMD_NAME}_analysis_\${logi}.log
do
  logi=\$((logi+1))
done

cp $SCRIPTDIR/analyze_field.sh .
./analyze_field.sh "$CMD_RA" "$CMD_DEC" "$CMD_NAME" $ARGS 2>&1 | tee ${CMD_NAME}_analysis_\${logi}.log

CMD="$CP * $OUTDIR"
echo \$CMD
\$CMD

EOF
