#!/bin/bash

# qmanyanalyze.sh - queue a few GLAST analysis runs on the Lyon cluster
# Stephen Fegan - sfegan@llr.in2p3.fr - 2008-10-31
# $Id$

PWD=`/bin/pwd`

if test "$TIMELIMIT" == ""; then TIMELIMIT=2500000; fi

FILENAME=$1
if test "FILENAME" == ""
then
  echo usage: $0 source_file [nlo=1] [nhi=0]
  exit
fi

if test \! -f "$FILENAME"
then
  echo File does not exists: "$FILENAME"
  exit
fi

NSTART=$2
if test "$2" == ""
then
  NSTART=1
fi

NEND=$3
if test "$3" == "" -o $3 -lt $2
then
  NEND=`wc $FILENAME | awk '{print $1}'`
fi

shift
shift
shift

ARGS="$@"

if test "$JOBPREFIX" == ""
then
  JOBPREFIX=COMBINED
fi

DATE=`date +%Y%m%d%H%M%S`
BASE_FILE=`basename $FILENAME`
SANITIZED_FILE=`sanitize_name.sh $BASE_FILE`
JOBNAME="-N ${JOBPREFIX}_${SANITIZED_FILE}_${NSTART}_${NEND}_${DATE}"

BASEDIR=`/bin/pwd`

# *****************************************************************************
# *****************************************************************************
#
# SCRIPT STARTS HERE
#
# *****************************************************************************
# *****************************************************************************


#cat <<EOF
qsub <<EOF
#!/bin/bash
#PBS -l t=${TIMELIMIT},M=512MB,platform=LINUX+LINUX32,scr=500MB,u_sps_glast
#PBS -eo -V $JOBNAME

###############################################################################
# Script automatically generated by $0 on behalf of $USER
###############################################################################

. \$HOME/.bash_profile
PFILES=.:\$PFILES
cd \$TMPBATCH
mkdir WORKSPACE

if test "$RUN"     \!= ""; then export RUN="$RUN"; fi
if test "$RESTART" \!= ""; then export RESTART="$RESTART"; fi

if test "$CLASS"   \!= ""; then export CLASS="$CLASS"; fi
if test "$FT2"     \!= ""; then export FT2="$FT2"; fi
if test "$FT1"     \!= ""; then export FT1="$FT1"; fi
if test "$IRF"     \!= ""; then export IRF="$IRF"; fi

if test "$TSTART"  \!= ""; then export TSTART="$TSTART"; fi
if test "$TEND"    \!= ""; then export TEND="$TEND"; fi
if test "$EMIN"    \!= ""; then export EMIN="$EMIN"; fi
if test "$EMAX"    \!= ""; then export EMAX="$EMAX"; fi
if test "$ZMAX"    \!= ""; then export ZMAX="$ZMAX"; fi
if test "$ROI"     \!= ""; then export ROI="$ROI"; fi
if test "$CONE"    \!= ""; then export CONE="$CONE"; fi
if test "$P1OPT"   \!= ""; then export P1OPT="$P1OPT"; fi
if test "$P1TOL"   \!= ""; then export P1TOL="$P1TOL"; fi
if test "$P2OPT"   \!= ""; then export P2OPT="$P2OPT"; fi
if test "$P2TOL"   \!= ""; then export P2TOL="$P2TOL"; fi

cp \$HOME/scripts/dree_analyze_field.sh .
cd WORKSPACE

for details in \`awk 'NR>=${NSTART}&&NR<=${NEND}' $FILENAME | sed -e 's/ /_/g'\`
do
  UNSANITISED_NAME=\`echo \$details | cut -d, -f1\`
  NAME=\`sanitize_name.sh "\$UNSANITISED_NAME"\`
  RA=\`echo \$details | cut -d, -f8\`
  DEC=\`echo \$details | cut -d, -f9\`

  OUTDIR=${BASEDIR}/\${NAME}
  if test \! -d \${OUTDIR}
  then
    mkdir \$OUTDIR
  fi

  if test "$RESTART" == "true" -o "$RESTART" == "pass1" -o "$RESTART" == "pass2"
  then
    cp -v \$OUTDIR/* .
  fi

  ../dree_analyze_field.sh "\${RA}" "\${DEC}" "\${NAME}" $ARGS

  cp -v * \$OUTDIR
  rm -f *
done
 
EOF
